name: login_signup_ui
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  password_rule_check: ^0.2.1
  http: ^1.2.0
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # ✅ App Icon
  flutter_launcher_icons: ^0.13.1

# ✅ Launcher icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CustomFontFamily
      fonts:
        - asset: assets/Fonts/Inika-Bold.ttf
